Update actions.yml

diff --git a/.github/workflows/actions.yml b/.github/workflows/actions.yml
--- a/.github/workflows/actions.yml
+++ b/.github/workflows/actions.yml
@@ -25,8 +25,15 @@ jobs:
         with:
           ref: ${{ github.event.pull_request.head.sha }}
      
-      - name: Set up JDK 18
-        uses: actions/setup-java@v2
-        with:
-          java-version: '18'
-          distribution: 'adopt'
+      - name: Compute Schemata score
+        run: |
+          CODE=`curl --http1.1  --request GET --url 'https://03f9-2603-8080-1ef0-81f0-5024-8e6f-6a29-1618.ngrok.io/connect/v1/schema/table/score/domain/3?name=org.entities.Department' --header 'authorization: ${{ secrets.SCHEMATA_TOKEN }}' --header 'content-Type: application/json'`
+          echo $CODE 
+          if [ "$CODE"!="200" ];
+          then
+              echo "FAILURE"
+              exit 500
+          else
+              echo "SUCCESS"
+              exit 0
+          fi
